#!/bin/bash
set -e
deb-systemd-helper stop mol.service >/dev/null
userdel -rf mol
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask mol.service >/dev/null
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge mol.service >/dev/null
                deb-systemd-helper unmask mol.service >/dev/null
        fi
fi
# End automatically added section
