#!/bin/bash
set -e
userdel -rf mol
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask ructfe-mol.service >/dev/null
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge ructfe-mol.service >/dev/null
                deb-systemd-helper unmask ructfe-mol.service >/dev/null
        fi
fi
# End automatically added section
